function [hfig, hax] = Visc_SR
% Plot viscosity as a function of Pe_R under confinement, where Pe_R is
% defined as gamma*h/U_0
dataDir = ['C:\Users\liux3141\Google Drive\Rheology of Bacterial Suspension\'...
        'Geometry-dependent viscosity\channelViscometer\Results\'];
load([dataDir 'viscDataSummary.mat']);
co = varycolor(10);
fname = fieldnames(viscDataSummary);
varname = genvarname(fname);
hfig = figure('Name', 'Viscosity - shear rate graph', 'NumberTitle', 'off', 'Resize', 'off');
hax = axes(hfig);

U0 = 22;
markerList = {'>', '<', 'd', 's', 'p', 'h', 'o', '+', '*', 'x'};
count = 1;
hold on
for j = 1: numel(fname)
    name = fname{j};
    if endsWith(name, 't')
        continue;
    end
    H = str2num(name(2:numel(name)));
    if H == 45
        continue;
    end
    subsdata = viscDataSummary.(fname{j});
    tdata = toTable(subsdata);
    hName = ['h' varname{j}];
    herrName = ['herr' varname{j}];
    eval([herrName ' = errorbar(hax, tdata(:, 1)*H/U0, tdata(:, 2), tdata(:, 3))']);
    eval([hName ' = line(hax, tdata(:, 1)*H/U0, tdata(:, 2))']);
    % Adjust line properties
    set(eval(hName),...
    'LineStyle', 'none',...
    'Marker', markerList{count},...
    'MarkerSize', 8,...
    'MarkerEdgeColor', 0.5*co(count,:),...
    'MarkerFaceColor', co(count,:));
    set(eval(herrName),...
    'LineStyle', 'none',...
    'Color', 0.5*co(count,:));
    if H >= 50
        set(eval(hName), 'MarkerFaceColor', 'none');
    end
    count = count + 1;
end
hold off
% Adjust axis and line properties
set(hax,...
    'FontSize', 16,...
    'Box', 'on',...
    'XLim', [0 80],...
    'YLim', [0 1.6],...
    'LineWidth', 1.5,...
    'XScale', 'linear',...
    'XMinorTick', 'on',...
    'YMinorTick', 'on');
hax.XAxis.MinorTickValues = 5:5:70;
hax.YAxis.MinorTickValues = 0.25:.5:1.5;

% hxlabel = xlabel('$\dot{\gamma}$\,(s$^{-1}$)', 'Interpreter', 'latex', 'FontSize', 24);
hxlabel = xlabel('$Pe_R=\dot{\gamma}h/v$', 'Interpreter', 'latex', 'FontSize', 24);
hylabel = ylabel('$\eta/\eta_0$', 'Interpreter', 'latex', 'FontSize', 24);
% Set up legends
hlegend = legend(...
    [hY25, hY30, hY37, hY38, hY50, hY58, hY83, hY90, hY100, hY128],...
    '$25$\,$\mu$m', '$30$\,$\mu$m', '$37$\,$\mu$m', '$38$\,$\mu$m',...
    '$50$\,$\mu$m', '$58$\,$\mu$m', '$83$\,$\mu$m', '$90$\,$\mu$m',...
    '$100$\,$\mu$m', '$128$\,$\mu$m');
% hlegend = legend(...
%     [hY25, hY30, hY37, hY38],...
%     '$25$\,$\mu$m', '$30$\,$\mu$m', '$37$\,$\mu$m', '$38$\,$\mu$m');
set(hlegend,...
    'Interpreter', 'latex',...
    'FontSize', 13,...
    'Location', 'southeast',...
    'NumColumns', 2);
end