load('angle_dependence_data.mat');
theta_deg = angle_dependence_data.theta;
v = angle_dependence_data.v;
line(theta_deg, v, 'LineWidth', 3);
line(theta_deg(theta_deg>=0&theta_deg<30), v(theta_deg>=0&theta_deg<30),...
    'LineWidth', 3, 'Color', 'r')
set(gca,...
    'FontSize', 16,...
    'Box', 'on',...
    'LineWidth', 1.5,...
    'XScale', 'linear')
ylabel('$\left<v^d\right>$ ($\mu$m/s)', 'interpreter', 'latex', 'FontSize', 24);
xlabel('$\theta$', 'interpreter', 'latex', 'FontSize', 24);